### ISSUE TITLE
When running scenarios in parallel, scenarios data is overwritten in the json files so report only shows half information

### ISSUE THREAD

**Issue by Sanj2005** [wswebcreation/multiple-cucumber-html-reporter#23] opened 2018-01-07 00:32 UTC
I am running scenarios in parallel on Browser Stack using 4 different feature files which has 2 scenarios (Examples) in each file.
So report is showing as 4 features and 4 scenarios which is wrong. Expected is it should 4 features & 8 scenarios.

Below are the configuration details:
```
{
 "cucumber": "^3.2.0",
 "protractor": "^5.2.2",
 "protractor-cucumber-framework": "^4.1.1",
"multiple-cucumber-html-reporter": "^1.4.1",
"protractor-multiple-cucumber-html-reporter-plugin": "^1.3.0",
nodeJs : V7.9.0
}
```

Sample Feature file 
```bash
Feature: **************************
  **********************************
  Background: ******************************
    ************ "****" ************************
  Scenario Outline: ************************
    Given ************ "****" ************************
    When U************ "****" ","<abc>","<xyz>","<pqr>","<rst>"
    Then User should complete the "****" ********* "<lmn>","<opq>" **********

  Examples:
  |abc         |xyz             |pqr             |rst        | lmn        |  opq    |
  |1             |4                 |7                |10        | 12          |  25      |
  |2             |5                 |8                |11        | 6            |  25      |
```

Here feature name is same & platform & browser combination is also same. But since I am running 8 scenarios in parallel, I am expecting the report should show 4 features & 8 scenarios on dashboard. And after clicking on each feature, it should show 2 scenarios in it. 
However currently if I click on feature file, it only shows 1 scenario. It means the json files which are generated are overwritten for the same features & browser/os combination, even though they ran for different scenario.
Note : There is no issue if I run directly features in parallel. This issue is coming only when I am running scenarios in parallel. Attaching the more files for clear understanding.

Please let me know if you need more data in order to fix this issue. Thanks in advance !!!

**Comment by Sanj2005** [comment] 2018-01-07 00:37
[TestSet_to_Upload.xlsx](https://github.com/wswebcreation/multiple-cucumber-html-reporter/files/1609398/TestSet_to_Upload.xlsx)
![report_dashboard](https://user-images.githubusercontent.com/31052167/34645361-c51e9cc6-f318-11e7-9bab-005687791a42.jpg)
![browserstack_executions](https://user-images.githubusercontent.com/31052167/34645362-c755b254-f318-11e7-90c8-3d35e1c62aeb.jpg)
![each_feature_contains_only_1_scenario](https://user-images.githubusercontent.com/31052167/34645363-c928bf72-f318-11e7-85cc-c540f8b78098.jpg)
![output_json_files_from_report_plugin](https://user-images.githubusercontent.com/31052167/34645367-fae62996-f318-11e7-97ab-ecaa1fc93457.JPG)

**Comment by Sanj2005** [comment] 2018-01-07 00:42
Summary of issue - 
1)HTML  Report Dashboard is correct for Features but not for scenarios
2) Each feature data on Report shows incorrect no of scnarios. In my case I ran 2 scenarios for each feature file. But it shows only 1 scenario against each feature file.

I hope I have given more  details about this issue. Please look into this & let me know as this is blocking me t use the Report. Thanks in advance !!!

**Comment by Sanj2005** [comment] 2018-01-07 00:44
``
exports.config = Object.assign(baseConfig, {
  directConnect: false,
    //seleniumAddress: 'https://' + `${globalConfig.browserstackUser}` + ':' + `${globalConfig.browserstackKey}` + '@hub-cloud.browserstack.com/wd/hub',
  seleniumAddress: 'https://hub-cloud.browserstack.com/wd/hub',
//--------------------------
  commonCapabilities: {
    'browserstack.user': `${globalConfig.browserstackUser}`,
    'browserstack.key': `${globalConfig.browserstackKey}`,
    'browserstack.debug': 'true',
    'browserstack.local': true,
    //'browserstack.localIdentifier': `${globalConfig.browserstackLocalIdentifier}`,
    acceptSslCerts: true,
    resolution: '1920x1080',   //1920x1080
    project: 'dg-pro-automation',
    build: pkg.name + ' ' + pkg.version + ' ' + getTimeStamp(),
    sharedTestFiles: true,
    getPageTimeout: '60000'
  },
//--------------------------
  multiCapabilities: jsonObj,

  plugins: [{
    package: 'protractor-multiple-cucumber-html-reporter-plugin',
    options: {
      automaticallyGenerateReport: true,
      removeExistingJsonReportFile: true,
      removeOriginalJsonReportFile: true,
      openReportInBrowser: true,
      saveCollectedJSON: true,
      reportName: 'DG Pre Sales Test Automation - Runtime Html Report',
      jsonOutputPath: './reports/report-plugin-json-output-folder/',
      reportPath: './reports/protractor-multiple-cucumber-html-report/',
      disableLog: false,
      metadataKey: 'deviceProperties',
      customData: {
        title: 'Run info',
        data: [
          {label: 'Application', value: 'DG Pre Sales'},
          {label: 'Execution Environment', value: process.env.npm_config_environment || `${globalConfig.executionEnvironment}`},
          {label: 'Application URL', value: process.env.npm_config_baseUrl || `${globalConfig.appURL}`},
          {label: 'Release', value: process.env.npm_config_releaseName || `${globalConfig.releaseName}`},
          {label: 'Cycle', value: process.env.npm_config_cycle || `${globalConfig.cycle}`},
          {label: 'Execution Start Time', value: `${executionTimeStamps.executionDateAndTimeStamp.start}`}
         // {label: 'Execution End Time', value: `${executionTimeStamps.executionDateAndTimeStamp.end}`}
        ]
      }
    }
  }],

**Comment by wswebcreation** [comment] 2018-01-07 08:27
Hi @Sanj2005 

This is most often not an issue with the module, but with the JSON files that are passed to the report. Can you first check if the data you save is unique enough, so I mean the JSON files your setup is generating before you give it to the report?

Tnx in advance

**Comment by Sanj2005** [comment] 2018-01-08 16:50
![output_json_files_from_report_plugin](https://user-images.githubusercontent.com/31052167/34681169-fe3a948c-f468-11e7-93e5-e2c3dd60c8ed.JPG)

Are looking for output json files which are generated below tag
 jsonOutputPath: './reports/report-plugin-json-output-folder/',

If yes, then I have attached those output json files here
https://gist.github.com/Sanj2005/bd71dbc3d35927fc622ad18fedb32ca4

**Comment by Sanj2005** [comment] 2018-01-08 17:32
If I run the features in parallel - I get below Report & below is the expected Report screen print.
Actually I expect the same Report, if I runs the same features & same scenarios but scenarios in parallel.

![expected_feature screen print](https://user-images.githubusercontent.com/31052167/34682368-bda2e4fc-f46c-11e7-88aa-d853d7d7ece8.JPG)

![expected_report dashboard](https://user-images.githubusercontent.com/31052167/34682362-bab1bad4-f46c-11e7-99ed-5ec3a7ead751.JPG)

And for this the jsons are created correctly when running features in parallel. Attaching those json files for your reference at below gist apth
https://gist.github.com/Sanj2005/1e45ea4eb99f46f44828d99fbe5c3cc6

Here (running the features in parallel) - the 2 scenarios in each features are in one output json file.
However if I run the scenarios in parallel, I guess it is generating the different 2 json file even though these 2 scenarios are from same feature file. And since the name of the output json file is same, it is overwriting it.

On other note, if I map different OS & browser against each 8 scenarios then I get different 8 json files.
This is also problem because I have only 4 feature file. So expected output josns should be 4 and each json should have 2 scenarios in it

I am trying to understand if we can generate the single json files if I run the scenarios in parallel case instaed of 2 json files. This will solve our problem to reflect correctly on the Report Dashboard & on each feature file report.

Please look into this & let me know if you need any further data from me. Thanks in advance !!!!

**Comment by wswebcreation** [comment] 2018-01-08 19:07
Thx for all the info, I still have a few question

- can you please share your Protractor config file
- what happens if you run in parallel and disable the reportingmodule completely, can you then also show the Jason files?

Based on that I think I have the answer.

**Comment by Sanj2005** [comment] 2018-01-08 19:28
Here is the protractor config files (based config & parallel config) along with input json file which is passed to multiCapabilities as a json oject
https://gist.github.com/Sanj2005/31163abba9c2912b993d2e904d648403

For your second point I will get back to you soon

**Comment by wswebcreation** [comment] 2018-01-08 20:03
@Sanj2005 

I think it is in the way you are running your tests. I never worked with the way you kick of your feature-files by running a specific line. I can understand that the name of the json files will be the same for both feature files. 
So you my assumption will be that without the report module enabled your setup will overwrite the files when you run them in parallel.

**What you could do:**
- Try also to set this option to `removeOriginalJsonReportFile : false`, because then you will keep your original files. The original files should also be less then you expect.
- Try also to add `shardTestFiles: true` per capability. `protractor-cucumber-framework` and my `protractor-multiple-cucumber-html-reporter-plugin` will add the `PID` to your files so the JSON files we be more unique.


Hope this will give you more insight

**Comment by Sanj2005** [comment] 2018-01-08 20:04
For your second point - 
If I remove my reporting module code as here https://gist.github.com/Sanj2005/6bfbba996222cacacc4b08cc951a3bcb 

then 
1) I will NOT get those jsons because they are coming through the reporting module using tags like -
 jsonOutputPath: './reports/report-plugin-json-output-folder/',
 reportPath: './reports/protractor-multiple-cucumber-html-report/',

2) And I wil get only josns created by cucumber using tag cucumberOpts

cucumberOpts: {
    strict: true,
    keepAlive: true,
    plugin: 'json',
    format: ['json:./reports/cucumber-json-files/' + getRandomIntInclusive(100, 1000000) + '_Results.json'],
        //format: 'json:./reports/json/' +  getTimeStamp() + '_Results.json',
    require: ['./features/step_definitions/dg_education_StepDefinitions_spec.js', './features/step_definitions/dg_StepDefinitions_spec.js', './features/step_definitions/webServicesStepDefinitions.js', './framework/core/baseHooks.js', './framework/core/reporting.js', './framework/env.js']
    //tags: argv.tags || globalConfig.tags
  },

I have kept those json files at gist below path -
https://gist.github.com/Sanj2005/c5ccff1e30bc58b4aadd90e86fabbfc1

Let me know your findings

**Comment by wswebcreation** [comment] 2018-01-08 20:18
@Sanj2005 , see my above comment, otherwise lets chat on Gitter before making a long thread here

**Comment by Sanj2005** [comment] 2018-01-08 22:21
Thanks for looking into it.
Actually I can not use Gitter here, as it is blocked in my company.
I checked above comment - So without reporting module, my setup will not overwrite the files as I have handled by adding some Random number logic and I also have sharedTestFiles: true in my Protractor parallel config file.
you can see those unique cucumber json files are generated uniquely at https://gist.github.com/Sanj2005/c5ccff1e30bc58b4aadd90e86fabbfc1

In the similar way, I also expect that Reporting module should also handle to generate the unique json files. If we have this, it will be really helpful.

Having said this, even if we generate the unique files for all scenarios at jsonOutputPath, this will not resolve my Report display issue fully as still, it will display multiple feature files on Report dashboard (as shown below)

![report_with_multiple_features_on_dashboard](https://user-images.githubusercontent.com/31052167/34694839-8f3d8b10-f496-11e7-8d59-e4beece399c6.JPG)


I guess this can be resolved if we can merge the files appropriately while generating the merged-output.json and enriched-output.json 

Here appropriately means -
1) If one feature has 2 scenarios and if we run scenarios in parallel, then we will get 2 different json files under "jsonOutputPath". But while merging them, the effective json should have 2 elements json objects under single feature file ( means it should check dynamically if the feature name is same then pull under elements array dynamically).

Let me know what you think in this case as this is going to simplify my issue to display the features correctly on report in I run the scenarios (Examples) in parallel

(Note : Triggering all the scenarios in parallel & getting the unique cucumber json output file for each scenario is already achieved in my framework)

**Comment by wswebcreation** [comment] 2018-01-09 04:58
Hi @Sanj2005 ,

Based on the above comment I can confirm that the module doesn't merge them by feature-file. This could be a new feature (care for a PR ;-)), but I don't know if this is worth the effort. You are the first that asks this and uses the execution of test this way, I never seen people run it like this.

I understand that in this case you would like to see 4 results (2 features for Chrome and 2 for Firefox) in the report, but for now you need to manage this in your own setup. The basic logic of this module is to:

1. read JSON-files from a given folder
2. process them
3. transform them to a nice report based on the given data

All other logic should be independently of the framework or the setup that is being used.

Can you verify if based on the above described 3 steps there is still an issue in the module, if not, please close the issue. It'll still be open for discussion, but I want to use the issues list for all issues ;-)

Tnx in advance

**Comment by Sanj2005** [comment] 2018-01-28 17:43
Hi wswebcreation,
so here after reading the cucumber output json files, while processing them is it possible for you to generate the merged json file by feature files. (All scenarios of a feature file should come under one feature file - parent tag). This will help to generate the scenario level report as well.
Please let me know.  Thanks !!!

**Comment by wswebcreation** [comment] 2018-01-30 05:08
Hi @Sanj2005 

As said in my comment above I don't see the added value of that. If you like to add a PR for it please feel free. For now I'm going to close this issue because it's not related to the module itself.

**Closed by wswebcreation** 2018-01-30 05:08 UTC
