### ISSUE TITLE
Problem with maxInstances>1

### ISSUE THREAD

**Issue by Doschdn1** [wswebcreation/multiple-cucumber-html-reporter#6] opened 2017-08-08 12:40 UTC
Hi,

when using maxInstances with a number > 1 the AfterFeature Hook tries to create the report every time a browser instance is closed. The problem is, if other instances are still running, the JSON File ist not yet finished and the parser throws an error instead of ignoring the files with size = 0 (these files are not yet finished).

14:37:09] E/launcher - e2e\utils\hooks.js:17 C:\Project\e2e\reports\multi\json_cucumber_chrome.13040.json: Unexpected end of JSON input
[14:37:09] E/launcher - SyntaxError: e2e\utils\hooks.js:17 C:\Project\e2e\reports\multi\json_cucumber_chrome.13040.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.readFileSync (C:\Project\node_modules\jsonfile\index.js:70:17)
    at files.map.file (C:\Project\node_modules\multiple-cucumber-html-reporter\lib\collect-jsons.js:22:32)
    at Array.map (native)
    at collectJSONS (C:\Project\node_modules\multiple-cucumber-html-reporter\lib\collect-jsons.js:22:11)

**Comment by wswebcreation** [comment] 2017-08-08 13:36
Hi @Doschdn1 

Can you place your config and your hook here? I think the problem is more in your configuration / hook then it is in this module, mainly because the module starts building when you / the script gives the call to do this.

**Comment by Doschdn1** [comment] 2017-08-08 14:26
Hi,

part of protractor.conf:

  multiCapabilities: [
    {
      'browserName': 'chrome',
      maxInstances: 3,
      'chromeOptions': {
        'args': ['show-fps-counter=true'],
      },
      cucumberOpts: {
        format: ['json:e2e/reports/multi/json_cucumber_chrome.json', 'pretty']
      },
	  shardTestFiles: true
     },
     {
       'browserName': 'firefox',
       maxInstances: 5,
       cucumberOpts: {
         format: ['json:e2e/reports/multi/json_cucumber_firefox.json', 'pretty']
       },
	   shardTestFiles: true
     },
     {
       'browserName': 'internet explorer',
       maxInstances: 5,
       cucumberOpts: {
         format: ['json:e2e/reports/multi/json_cucumber_ie.json', 'pretty']
       },
	   shardTestFiles: true
    }
  ],

and part of hooks:

  this.registerHandler('AfterFeature', function(features, callback) {
    var reporter = require('multiple-cucumber-html-reporter');
    reporter.generate({
        jsonDir: './e2e/reports/multi/',
        reportPath: './e2e/reports/'
    });
    callback();
  });
};

The call is performed every time when a browser is closed. The browser is closed after a scenario is finished and at this moment it could be possible that an other browser or browser instance is holding a JSON file for an other feature which has a file length of 0.

**Comment by wswebcreation** [comment] 2017-08-08 14:40
Tnx,

You are using: 

- the afterFeature hook
- CucumberJS to automatically save the json

I would advice to do it like you can see [here](https://github.com/wswebcreation/perfecto-webinar-protractor/tree/typescript/config-helpers) or [here ](https://github.com/wswebcreation/protractor-cucumber-typescript-boilerplate/tree/master/e2e-tests/config/helpers). There you have a report hook that will do all for you.

I'm going to close the issue because the issue is not in this module, but in delivering / generating the files.

**Closed by wswebcreation** 2017-08-08 14:40 UTC
Labels: needs more info, question
