### ISSUE TITLE
The error_message is missing in the html report  in case of before hook failure

### ISSUE THREAD

**Issue by jijojose1691** [wswebcreation/multiple-cucumber-html-reporter#175] opened 2022-04-29 17:28 UTC
**Environment :**
 - multiple-cucumber-html-reporter: 1.20.0
 - Node.js version: 16.14.2
 - NPM version: 5.8.0
 - Platform name and version: . Windows 10]
 - Cucucmber version: 6.0.5

**Describe the bug**
As part of tet automation, I am using cucumber JS to automate tests and I am using multiple-cuumber-html reporter to generate reports. I started to notice that with the latest version of the library the error message is missing in the report if any failure happened in the Before hook. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Found the same issue in the demo URL, which is attached in the master repo: https://wswebcreation.github.io/multiple-cucumber-html-reporter/browsers/index.html
2. Choose the feature named Before Error
3. Check the failure reason in UI
4. The user is unable to identify the reason behind the failure. But the Error message is present in the sample report, https://github.com/wswebcreation/multiple-cucumber-html-reporter/blob/main/test/unit/data/json/before.hook.error.jso.n Refer to line 32 for the error message.

**Expected behaviour**
The error message should present to the user so that the user will get to know why the test step failed. 

**Additional context**
Note - The feature was working before in the previous release long back. Not sure about the version.

**Comment by BaCaRoZzo** [comment] 2022-04-30 13:27
@jijojose1691 there was indeed a change in behaviour between `v1.16.1` and `v1.16.2` - full diff [here](https://github.com/wswebcreation/multiple-cucumber-html-reporter/compare/v1.16.1...v1.16.2). In `v1.16.1` the `Before` is visible whereas in the subsequent patch release it is not.

However, the behaviour of `v1.16.2` is the correct one since the step you are taking as example [is `hidden`](https://github.com/wswebcreation/multiple-cucumber-html-reporter/blob/main/test/unit/data/json/before.hook.error.json#L25). If you remove the `hidden` key and generate the report with latest `v1.20.0` the step correctly shows up.

So it's either hidden as well on your side or another problem is affecting your setup. In the latter case, I'm pretty sure, an example `json` would surely help our beloved maintainer to debug the issue. :slightly_smiling_face:

**Comment by jijojose1691** [comment] 2022-05-02 08:48
@BaCaRoZzo I confirmed that the value is hidden in my Before failure. Once I changed the value of hidden to false it started working. Do you know to make the value of hidden to true during test execution?

**Comment by BaCaRoZzo** [comment] 2022-05-02 14:32
@jijojose1691 nope, I'm sorry. We use a pretty straigthfoward `./node_modules/.bin/cucumber-js --format=node_modules/cucumber-pretty` in our setup and `Before` are visible, AFAICT.

**Comment by wswebcreation** [comment] 2022-05-07 11:53
Thanks for the support @BaCaRoZzo 

Closing this issue now because it works as intended

**Closed by wswebcreation** 2022-05-07 11:53 UTC
