### ISSUE TITLE
Unable to open detailed feature report after the recent change

### ISSUE THREAD

**Issue by ThulasiramanK** [wswebcreation/multiple-cucumber-html-reporter#112] opened 2020-02-17 13:57 UTC
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: [e.g. 1.15.0]
 - Node.js version: [e.g. 8.9.1]
 - NPM version: [e.g. 5.8.0]
 - Platform name and version: [e.g. Windows 10]
 - Cucucmber version: [e.g. 4.2.0]

**Config of multiple-cucumber-html-reporter**
An example of how you configured the reporter in your config

**Describe the bug**
Unable to open detailed feature report after the recent change

**To Reproduce**
Open the html report
Click on any feature link in the report to open detailed report

[Include code or an example repository that can easily be set up]

**Expected behavior**

**Log**
If applicable, add logs to help explain your problem. If you don't have log, enable 'debug:true' in the config and paste the log here.
Please use proper markdown to style it

**Additional context**
![image](https://user-images.githubusercontent.com/61151609/74660092-77199980-5163-11ea-9520-efb34f6fde8b.png)

**Comment by wswebcreation** [comment] 2020-02-17 15:15
@ThulasiramanK 

Thanks, I'm on it

**Comment by wswebcreation** [comment] 2020-02-17 15:19
Found it, issue was in here https://github.com/LuizFelipeNeves/multiple-cucumber-html-reporter/blob/cebb5fe5d9076304441d0add866a6f9d19c1d152/templates/feature-overview.index.tmpl#L26

The files needed to get the assets from the root level, making a release now

**Comment by wswebcreation** [comment] 2020-02-17 15:24
@ThulasiramanK 

Can you install https://github.com/wswebcreation/multiple-cucumber-html-reporter/releases/tag/v1.15.1. That one should fix it

**Comment by ThulasiramanK** [comment] 2020-02-17 16:15
Thanks for addressing the issue. Let me install new version and check.

Thulasi

**Comment by wswebcreation** [comment] 2020-02-22 14:18
Closing it because after testing it myself the issue is resolved

**Closed by wswebcreation** 2020-02-22 14:18 UTC
Labels: bug
