### ISSUE TITLE
Invalid characters being reported

### ISSUE THREAD

**Issue by kappa10j** [wswebcreation/multiple-cucumber-html-reporter#46] opened 2018-05-01 17:40 UTC
I see the following in the report:

[
  **"��^�,e",**
  [
    {
      "key": val
    }
  ]
]

This happens for the following cucumber JSON results:
"embeddings": [
              {
                "data": **"orderCxl"**,
                "mime_type": "text/plain"
              },
              {
                "data": "[{\"key\":val}]",
                "mime_type": "application/json"
              }
            ]

It only happens when the data is orderCxl.  For any other value for the first data, it reports correctly.

**Comment by wswebcreation** [comment] 2018-05-02 04:04
Hi @kappa10j 

Can you post the complete JSON file. As far as I can see this is not a problem with the reporter but with the data you put into it. For example 

```
"embeddings": [
{
"data": "orderCxl",
"mime_type": "text/plain"
},
{
"data": "[{"key":val}]",
"mime_type": "application/json"
}
]
```
is not valid, `"[{"key":val}]"` should be escaped like this `"[{\"key\":val}]"`

**Comment by kappa10j** [comment] 2018-05-02 12:43
Hi,

I can't send the entire json because it's not permistted from within my
company.  But I had just left out the quotes.

"embeddings": [
{
"data": "orderCxl",
"mime_type": "text/plain"
},
{
"data": "[{\"id\":546461}]",
"mime_type": "application/json"
}

**Comment by wswebcreation** [comment] 2018-05-02 13:33
@kappa10j 

And this messes up the report?

**Comment by kappa10j** [comment] 2018-05-02 13:38
yes.  it seems to be the word orderCxl.  When I pass any other word, it's
fine.

**Comment by wswebcreation** [comment] 2018-05-02 13:45
I need to check it where it's going wrong, could be some encoding. Currently I don't have enough time to do it, will come back on it later

**Comment by binubeee** [comment] 2019-07-09 19:36
Any update on this ? I'm facing the same issue. Appreciate if you can suggest a workaround for time being atleast. Thanks in advance

**Comment by BaCaRoZzo** [comment] 2022-04-27 11:36
>Appreciate if you can suggest a workaround for time being atleast. Thanks in advance

For the reader, the problem is indeed on the encoding side. `orderCxl` is a valid `base64` string. The code checks for that and [decodes the string](https://github.com/wswebcreation/multiple-cucumber-html-reporter/blob/main/lib/generate-report.js#L349) causing the problem. One can encode the string beforehand so that it's decoded to the right final string.

@wswebcreation would it make sense to just print the `text/plain` mimetype instead of trying to convert it? Or are you supporting some specific case here? It seems a bit counter-intuitive to have this behaviour and should be a user duty to provide printable content in the `text/plain` type, I think. :thinking: 
Alternatively we can clearly state the behaviour in the docs and point to the workaround.
If I can contribute with any of those, more than happy. :slightly_smiling_face:

**Comment by wswebcreation** [comment] 2022-05-07 12:03
I thought I needed to make it fool proof by escaping as much as possible, this can be reverted and let it break if people provide incorrect info. So feel free to submit a fix @BaCaRoZzo

**Comment by wswebcreation** [comment] 2022-05-22 05:59
Closing this one thanks to the PR of @BaCaRoZzo , we will proceed the the conversation there

**Closed by wswebcreation** 2022-05-22 05:59 UTC
Labels: bug, low priority

**Comment by fadomire** [comment] 2023-03-13 11:32
Hello,

i'm running into issues caused by the change in this PR #177 

The problem is that most cucumber libraries (cucumber-jvm, cucumber-js, ...) do base64 encode text/html and text/plain attachements (embedding)
https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/attachments.md
https://github.com/cucumber/common/issues/1116

I feel that this PR fix a small bug for cases where string can be decoded as base64 and are then wrongly decoded.
But introduce regression for most users based on how major cucumber libraries output text/html in the json output.

Would it be possible that i open a PR to reintroduce base64 decoding ?
