### ISSUE TITLE
Not able to view SCENARIO OUTLINE example data set value in report html steps

### ISSUE THREAD

**Issue by id4automation** [wswebcreation/multiple-cucumber-html-reporter#69] opened 2018-10-23 14:29 UTC
I am not seeing the data variables in their respective scenario steps while reading the cucumber html report.

The Examples value are appearing for the scenario outline steps, if the data is passed inline.. 
like below. Here <username> and <password> values are getting replaced with the corresponding iteration data on each individual scenario
Scenario Outline:
Given I login as a user "<username>" and password "<password>"
Examples:
|username|password|
|userOne|passOne|
|userTwo|passTwo|

But the Scenario Outline Example data is not appearing and the placeholder appears null. 
Scenario Outline:
Given I login to the application with the below data
|getUsername|getPassword|
|<username>|<password>|
Examples:
|username|password|
|userOne|passOne|
|userTwo|passTwo|

![image](https://user-images.githubusercontent.com/41796998/47367731-324d3200-d6d8-11e8-884f-b9a47c6a00e8.png)

**Comment by wswebcreation** [comment] 2018-10-24 18:03
Hi,

First of all can you use the template and provide all the needed info? Without it I can't help you and this issue will be closed

**Comment by id4automation** [comment] 2018-10-25 11:15
Hiya. Kinldy let me know what more information is required.  
To put in simple, If I pass a datatable with the default values in it, they appear on the report. 

If the datatable gets the values from the EXAMPLE set, then they are not appearing on the report .

Expected: For a scenario outline , the datatable values for the corresponding run needs to be displayed

**Comment by wswebcreation** [comment] 2018-10-25 11:46
A scenario outline will not be shown as an outline but as separate scenario's. The values are also shown in the report.
If not please check your original JSON which is created by Cucumber. This module only parses that.

Extra info needed is in the template you removed 😉.
Like reporter version, node version, cucumber version and an example JSON file (so before parsed by the module)

**Comment by id4automation** [comment] 2018-10-26 15:46
**Environment (please complete the following information):**
 - multiple-cucumber-html-reporter: 1.11.2
 - Node.js version: v8.9.1
 - NPM version: 6.4.1
 - Platform name and version: Windows 10 
 - Cucumber version: 4.1.0

**Config of webdriverio + multiple-cucumber-html-reporter**
I am currently using the wdio-multiple-cucumber-html-reporter. 

**Describe the bug**
In Multiple html report, I understand a scenario outline will not be shown as an outline but as separate scenario's. The values are also shown in the report.
The values do appear when the steps has the value either hard coded in the same line or in the data table. Example:
Example 1 : [Hardcoded in the steps ]
Given I login as user "abc@xyz.com" and password as "test1234"
Example 2 : [Passed by Example to the steps ]
Given I login as user "<varEmail>" and password as "<varPassword>"
Example 3 : [Hardcoded in the step's datable ]
Given I login into the application
|username|password|
|abc@xyz.com|test1234|


But the values are not appearing in the report if they are passed to a data table from Scenario outline EXAMPLE 
Example 4: [Hardcoded in the step's datable ]
Given I login into the application
|username|password|
|<varEmail>|<varPassword>|


If not please check your original JSON which is created by Cucumber. This module only parses that.

**To Reproduce**
Steps to reproduce the behavior:
Attached a json file generated by cucumber that can be used

[Include code or an example repository that can easily be set up]
[testReport.json.log](https://github.com/wswebcreation/multiple-cucumber-html-reporter/files/2519870/testReport.json.log)

**Expected behavior**
I understand the values needs to be updated by CUCUMBER which I think I need to follow it up a


 seperate issue. But currently the values are appeaing blank, eventhough the json file has <variableName> in it

Hope this one should be precise. apologies for ignoring the template data

**Comment by wswebcreation** [comment] 2018-10-26 17:29
Aha, please submit this issue to the wdio-multiple-cucumber-html-reporter and also provide your version of cucumber-framework (the one that is in your package.json and package-lock.json

I think the issue is in your version of that one. I'm going to close it here

**Closed by wswebcreation** 2018-10-26 17:29 UTC
Labels: needs more info
